---
  - name: Instalação do pacotes 
    apt:
      pkg:
      - mysql-client
      - libmysqlclient-dev
      state: present
      update_cache: yes

  - name : criando usuario wpuser
    mysql_user:
        name: "wpuser"
        password: "Wp@12345"
        priv: '*.*:ALL'
        host: "%"
        state: present   
  